### ISSUE TITLE
[V50] Many Error, for example cause blob, double wing update issues

### ISSUE THREAD

**Issue by CoolLKKPS** [Ian0526/SnatchinBracken#10]
same as topic

**Comment by CoolLKKPS** [comment]
@Ian0526

**Comment by Ian0526** [comment]
I'm sorry, do you have more information?

**Comment by CoolLKKPS** [comment]
u can simply use dev mode to spawn those creature, and u will see creature update issues in ur log console

**Comment by Ian0526** [comment]
Should be patched, let me know if there are still issues.

**Comment by CoolLKKPS** [comment]
yea that fixed
