### ISSUE TITLE
LethalConfig is required for SnatchinBraken to work correctly 

### ISSUE THREAD

**Issue by zndrmn** [Ian0526/SnatchinBracken#12]
The config file doesn't generate when LethalConfig isn't present. When the config is present (without LethalConfig) it gets completely ignored, and most features seem outright broken.

Mods installed: 
[GameMaster 3.2.0](https://thunderstore.io/c/lethal-company/p/GameMasterDevs/GameMaster/) (used to make testing easier; initially saw this bug without this installed)
[LethalConfig 1.4.0](https://thunderstore.io/c/lethal-company/p/AinaVT/LethalConfig/)
SnatchinBracken 1.4.7

**Comment by Ian0526** [comment]
Fixed, thank you.
