### ISSUE TITLE
Shovel Issue After Being Snatched

### ISSUE THREAD

**Issue by EchoLWS999** [Ian0526/SnatchinBracken#4]
This is one of my favorite mods! I wanted to tell you that if you have a shovel on you when the Bracken snags you, if you are freed from the Bracken by a teammate before your death, your shovel becomes bugged in a way where you can't swing it. You can swing other shovels fine, just not that one. 

I would also request that you consider adding a feature where at a percentage of the time after "gradual damage" is enabled it plays the "oxygen critically low" message it plays when you're drowning. I'd also suggest slowly blacking the players screen out over time

**Comment by Ian0526** [comment]
I’ll give this a lookies, thank you. As for the ideas, I like them. I think
the critically low message is client based tho, just pops up when your HP
is low enough and you get damaged

**Comment by Ian0526** [comment]
@EchoLWS999 I just tested, and wasn't able to reproduce. Are you able to get a recording for me?

**Comment by EchoLWS999** [comment]
@Ian0526 I can try, it may turn out to be a mod incompatibility

**Comment by Ian0526** [comment]
Any more information? @EchoLWS999

**Comment by EchoLWS999** [comment]
@Ian0526 

I've been kinda putting it off kinda not, I apologize! I did some testing and I can confirm it is not caused by your mod. There is some.. unknown mod in my pack that causes getting grabbed by the snare flea or the Bracken to make you unable to swing your shovel after being freed. Needless to say, this isn't on you and you can mark this post as closed. Thanks for testing it for me so quickly!

**Comment by Ian0526** [comment]
Gotcha, well let me know if you figure out the culprit. Maybe there's something I can do to patch it myself.
