### ISSUE TITLE
[Might be issue] host won't take any dmg (if bracken grab a person and after a round)

### ISSUE THREAD

**Issue by CoolLKKPS** [Ian0526/SnatchinBracken#8]
quote this issue bc im not sure:
https://github.com/Malcolm-Q/LC-LateGameUpgrades/issues/354

**Comment by Ian0526** [comment]
This issue seems like it relates to rejoining. Did you mean to link this one?

**Comment by CoolLKKPS** [comment]
no they didn't rejoin the game, they always in my lobby (or i miss something)
i have to test more deeper, since this issue is very random, need take sometimes

**Comment by Ian0526** [comment]
Might be fixed with today's build. Let me know how it works.

**Comment by CoolLKKPS** [comment]
still testing, but not sure if this issue already fixed by other mods, idk weird, if this issue happen again will reopen this issue
