### ISSUE TITLE
[For User/Dependencies missing] 1.4.3 need LethalConfig to work properly

### ISSUE THREAD

**Issue by CoolLKKPS** [Ian0526/SnatchinBracken#9]
did i miss something?

Edit: i didn't
Edit: No i did miss something...

**Comment by CoolLKKPS** [comment]
@Ian0526 ok that might be the problem, config file did not generate and update

**Comment by CoolLKKPS** [comment]
for user or modpack creator, those are add in the config file:
> \#\# Time in seconds until Bracken automatically kills when grabbed. Range: 1-60 seconds.
> \# Setting type: Int32
> \# Default value: 15
> Seconds Until Auto Kill = 15

\#\# The Bracken's power level. Each moon has a different Power Level that allows a certain number of monsters to spawn in. Look it up for more information.
\# Setting type: Int32
\# Default value: 3
Bracken Power Level = 3

**Comment by Ian0526** [comment]
It should auto update, did yours not?

**Comment by CoolLKKPS** [comment]
pretty sure no

**Comment by Ian0526** [comment]
What mod manager are you using? R2, Thunder? Or are you manually adding the dll

**Comment by CoolLKKPS** [comment]
R2 actually

What mod manager are you using? R2, Thunder? Or are you manually adding the dll

**Comment by Ian0526** [comment]
Very weird, I've added ten or so config options throughout the updates of this project and that hasn't ever happened. I just tried it on an outdated pack, updated, and the config option loaded fine.

**Comment by CoolLKKPS** [comment]
uh something shown in my log:
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'LethalConfig, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
SnatchinBracken.SnatchinBrackenBase.Awake () (at <e8785961d9a24f60ba529f0677698fda>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

**Comment by CoolLKKPS** [comment]
so this need LethalConfig to work properly? let me check

**Comment by CoolLKKPS** [comment]
ok yes, so bc i run this mod in a brand new profile, and R2 didn't auto download LethalConfig (actually was another setting mod), cause this issue

**Comment by CoolLKKPS** [comment]
im dumb, i didn't see this error log before bc it even not show up for unknow reason, but it worked now so weird i guess
anyway thx for the reply, i figured it out, and uh have a good day

**Comment by Ian0526** [comment]
It was due to Lethal Config not being present, I accidentally added in the reference.
